(library
 (name buscar_backend_lib)
(modules types config database cache auth repository vehicle_commands swagger fipe)
  (libraries
   dream
   lwt
   lwt.unix
   caqti
   caqti-lwt
   caqti-lwt.unix
   caqti-driver-postgresql
   yojson
   ppx_deriving_yojson.runtime
   cryptokit
   redis-lwt
   redis
   uuidm
   ptime
   ptime.clock.os
   logs
   logs.fmt
  fmt
  cohttp-lwt-unix
  conduit-lwt-unix
  lwt_ssl)
 (preprocess (pps ppx_deriving_yojson)))

